### ISSUE TITLE
ReSharper 9.0 support

### ISSUE THREAD

**Issue by fakhrulhilal** [joaroyen/ReSharperExtensions#7]
Is there any plan to support ReShaper v9? I'm using v9 update 1 currently.

**Comment by joaroyen** [comment]
This is a very timely question, because I’ve been working on an update for a couple of weeks :)

There are som big changes in how extensions are distributed in ReSharper 9.0, and I opted to keep it simple and create a brand new extension for ReSharper 9.0 (that is ReSharper Wave01 of products). The package should be up on the ReSharper gallery, and you can find the source here: https://github.com/joaroyen/ReSharper.LiveTemplates.

Thanks for using the extension and please let me know if you have any issues.

**Comment by fakhrulhilal** [comment]
Unfortunately, I can't install this plugin using R# extension manager. I tried using manual install as defined in **Alternative 2** but it didn't work either. The macro for template is interesting feature. I tried to create pascal case naming rather than snake case naming convention.

**Comment by joaroyen** [comment]
As far as I know, every extension is installed through the extension manager, and I'm not sure if it is possible to install it manually in ReSharper 9.0.

If you can't access the official feed, you can try to build the NuGet package locally using the BuildExtension.ps1 PowerShell script. This build script puts the NuGet package in the Extensions folder and you can then add your local folder as a feed in ReSharpers options page for the Extension Manager.

**Comment by citizenmatt** [comment]
Yeah, you have to install extensions through the extension manager with 9.0. If you're having issues with the extension manager, please email support at jet brains, or raise an issue at https://youtrack.jetbrains.com

**Comment by fakhrulhilal** [comment]
I'll try using local folder as nuget feed. Thanks for help.
